version: '3.8'

services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: eksiclone-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=eksiclone
      - RABBITMQ_DEFAULT_PASS=eksiclone_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - eksiclone-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  eksiclone-network:
    driver: bridge
volumes:
  rabbitmq_data:
